# Generated by Django 5.0.6 on 2024-07-09 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankstatements',
            fields=[
                ('bankstatementID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bankstatements',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('bankstatementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bankstatements')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
